### PR TITLE
updated icons

### PR DESCRIPTION
**Pull request by AndyHaoT**
Have a look at those new icons

### CODE REVIEW

**Review by turnervink — COMMENTED** [review]
Are we agreed on not using the shopping cart for the list icons anymore? I thought we found people understood it well.

**Comment by AndyHaoT** [comment]
Shopping cart still seems like too much emphasis on purchasing for me.
Another reason I choose the list is to make it consistent with the low waste icon on the same page

**Comment by AndyHaoT** [comment]
I also changed the hamburger menu icon because I felt like we have established a slim style, so I tried to match it.

**Review by turnervink — APPROVED** [review]
Looks good for now. Let's test these new icons if we have time.

**Pull request merged**
